apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kwjg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kwjg
    app.kubernetes.io/part-of: tkrw-pr712-0075-0023-app
  name: devfile-sample-kwjg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-kwjg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-kwjg
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0023-tenant/tkrw-pr712-0075-0023-app/devfile-sample-kwjg@sha256:b511738955b86bb74cb23cfba78954223abbffc6bf7d467095484d07511af754
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
